#!/usr/bin/env bash

rm -r "$(pwd)/assets"
docker rm -f container-ship
docker ps -qaf label=ctr-ship.deployment | xargs docker rm -f

mkdir -p "$(pwd)/assets/manifests"
mkdir -p "$(pwd)/assets/nodes"
mkdir -p "$(pwd)/registry"

# up container ship
docker run -d --name container-ship \
  -v "$(pwd)/assets":/assets \
  -p 127.0.0.1:8443:8443 \
  -e ENDPOINT=host.docker.internal:8443 \
  --restart always \
  --log-driver json-file \
  --log-opt max-size=128k \
oxmix/container-ship

sleep 3

echo 'Add machine to nodes'
curl -kX POST https://127.0.0.1:8443/nodes/apply --data-binary @- << 'EOF'
IPv4: 172.17.0.1
name: localhost
deployments:
  - ctr-ship.registry-deployment
  - my-project.redis-deployment
EOF

echo 'Connect machine, installing cargo-deployer'
curl -sk https://127.0.0.1:8443/connection | bash -

echo 'Add manifest docker registry'
curl -kX POST https://127.0.0.1:8443/deployment --data-binary @- << EOF
space: ctr-ship
name: registry-deployment
containers:
  - name: registry
    from: registry:2
    stop-time: 30
    volumes:
      - `pwd`/registry:/var/lib/registry
    ports:
      - 127.0.0.1:5035:5000

  - name: nginx
    from: nginx
    volumes:
      - `pwd`/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8030:80
EOF

echo 'Add manifest example redis'
curl -kX POST https://127.0.0.1:8443/deployment --data-binary @- << 'EOF'
space: my-project
name: redis-deployment
containers:
  - name: redis
    from: redis:6-alpine
    command: redis-server --save "" --appendonly no
EOF

echo '----------'
echo Open http://localhost:8030