#!/usr/bin/env bash
set -e

NAME='cargo-deployer'
HUB='oxmix'

case $1 in
  push)
    ! docker buildx rm $NAME-builder
    trap 'docker buildx rm $NAME-builder' EXIT
    docker buildx create --name $NAME-builder --use
    docker buildx build . --push \
      --tag $HUB/$NAME:latest \
      --platform linux/amd64,linux/arm64
    docker buildx prune -f
    ;;

  local)
    docker build -t $HUB/$NAME:latest .
    ;;

  *)
    echo "./build local|push"
    ;;
esac
