name: Build and publish

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build containers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building container-ship images and push to hub
        run: |
          set -e
          ./build tests
          docker run --privileged --rm tonistiigi/binfmt --install arm64
          docker buildx create --use
          docker buildx build --tag oxmix/container-ship:1 \
                              --tag oxmix/container-ship:latest \
                              --push --platform linux/amd64,linux/arm64 .

      - name: Building cargo-deployer images and push to hub
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64
          docker buildx create --use
          docker buildx build --tag oxmix/cargo-deployer:1 \
                              --tag oxmix/cargo-deployer:latest \
                              --push --platform linux/amd64,linux/arm64 cargo-deployer